import type { Metadata } from 'next';
import { Outfit, Geist } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const outfit = Outfit({
    variable: '--font-outfit',
    subsets: ['latin'],
});

const techovier = localFont({
    src: './fonts/Techovier.otf',
    variable: '--font-techovier',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="fr"
            className={cn("h-full", "antialiased", outfit.variable, techovier.variable, "font-sans", geist.variable)}
        >
            <body className="min-h-full flex flex-col font-outfit">
                {children}
            </body>
        </html>
    );
}
